In [2]:
import numpy as np
import tensorflow as tf

**tensor - it is a multidimensional array because tensorflow takes    input as multidimensional arrays**

**The difference between a NumPy array and a tensor is that the tensors are backed by the accelerator memory like GPU and they are immutable, unlike NumPy arrays**

•	**Constant tensors** – Used to create Tensor from tensor like object list

•	**Variable tensors** – The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods

In [1]:
# creating a sample constant and a variable tensor
a = tf.Variable(0)
b = tf.constant(1)

NameError: ignored

In [8]:
mid = tf.add(a,b)


In [15]:

tf.__version__

'2.8.2'

**Constant Tensor**

In [18]:
# a sample constant tensor 
tensor = tf.constant([[[[1,2,3],
                       [4,5,6],
                       [7,8,9]]]])
tensor

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]], dtype=int32)>

In [19]:
# this shows the number of dimension of the tensor or the empty matrix wrapping around the tensor data
tensor.ndim

4

In [20]:
const = tf.constant([1,2,3])
const


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

**Variable Tensor**

In [24]:
# creating a variable tensor
change = tf.Variable([10,11])
change

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>

In [26]:
# we can assign a new value to a variable tensor but not the constant tensor
change[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 2, 11], dtype=int32)>

In [27]:
change

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 2, 11], dtype=int32)>

In [3]:
# 2 dimension tensor or matrix
rank2_tensor = tf.constant([[10,4],
                            [5,8]])

rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  8]], dtype=int32)>

In [ ]:
# add another dimension or increase its shape without adding new elements
# tf.shape[ndim,row,columns]

In [6]:

rank3_tensor = tf.expand_dims(rank2_tensor, axis=0)
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  4],
        [ 5,  8]]], dtype=int32)>

In [7]:
rank4 = tf.expand_dims(rank2_tensor, axis=1)
rank4

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  4]],

       [[ 5,  8]]], dtype=int32)>

In [8]:
tens = tf.constant([[2,3],[4,5]])
tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

# Mathematical operations on tensors

In [13]:
# addition operation on tensors
add = tens + 10


In [14]:
add

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [15]:
X = tf.constant([[1,2],[2,3],[3,4]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [27]:
Y = tf.constant([[5,6,4,1],[6,7,5,5],[7,8,3,2]])
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 6, 4, 1],
       [6, 7, 5, 5],
       [7, 8, 3, 2]], dtype=int32)>

#✋ What is difference between Expand dims and reshape?
Expand_dims – They increase the dimension of the tensor 
Reshape – it changes the shape of the tensor without increasing its dimension.
Ex. (2,3) -> (3,2) 


In [34]:
Y = tf.reshape(Y, shape = (4,3))

# Transpose
transpose only changes the orentation of the matrix the rows shifts to columns and columns to rows.

In [31]:
tf.transpose(Y)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 6, 7],
       [6, 7, 8],
       [4, 5, 3],
       [1, 5, 2]], dtype=int32)>

In [35]:
Y,X

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 6, 4],
        [1, 6, 7],
        [5, 5, 7],
        [8, 3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>)

# Matrix multiplication –
**Matrix multiplication can be done using:**
1.	 **Tf.matmul( )**
2.	 **Tf.tensordot( )**


In [39]:
tf.matmul(Y,X)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[29, 44],
       [34, 48],
       [36, 53],
       [20, 33]], dtype=int32)>

In [40]:
tf.tensordot(Y, X , axes=1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[29, 44],
       [34, 48],
       [36, 53],
       [20, 33]], dtype=int32)>

In [41]:
#Aggregation of tensors
agg = tf.constant(np.random.randint(1,50, size=30))

In [55]:
agg = tf.cast(agg, dtype=tf.float16)
agg

<tf.Tensor: shape=(30,), dtype=float16, numpy=
array([47.,  3., 27., 40., 24., 21., 49.,  5., 45.,  4., 46.,  4., 35.,
       15., 40., 22., 49.,  9., 41., 48., 42., 31., 20., 36., 41., 46.,
       33., 41., 15., 34.], dtype=float16)>

In [47]:
# tf.reduce_min shows the minimum value of a tensor
tf.reduce_min(agg)

<tf.Tensor: shape=(), dtype=float16, numpy=3.0>

In [83]:
# tf.reduce_max finds the maximum vlaue of a tensor
tf.reduce_max(agg)


<tf.Tensor: shape=(), dtype=float16, numpy=49.0>

In [84]:
# Shows the index at which the max value occours
tf.argmax(agg)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [49]:
# Find the mean 
tf.reduce_mean(agg)

<tf.Tensor: shape=(), dtype=float16, numpy=30.44>

# Variance and Standard deviation

In [51]:
#Find variance of tensor

import tensorflow_probability as tfp

tfp.stats.variance(agg)

<tf.Tensor: shape=(), dtype=float16, numpy=224.9>

In [54]:
#Find the standard deviation

tf.math.reduce_std(agg)

<tf.Tensor: shape=(), dtype=float16, numpy=14.99>

In [77]:
# Positional minimum and maximum
pos = tf.constant([[[9,8,3],[4,7,5],[6,2,1]]])
pos

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[9, 8, 3],
        [4, 7, 5],
        [6, 2, 1]]], dtype=int32)>

In [78]:
# Minimum of a tensor position

tf.reduce_min(pos[:,1:2,:])

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [81]:
# Maximum of a tensor position

tf.reduce_max(pos[:,2:3,:])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [88]:
# Squeezed
tf.random.set_seed(32)

sq = tf.constant(tf.random.uniform(shape=[30]), shape=(1,1,1,30))
sq

<tf.Tensor: shape=(1, 1, 1, 30), dtype=float32, numpy=
array([[[[0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
          0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
          0.01469815, 0.86204493, 0.12014258, 0.91072273, 0.00848019,
          0.62772846, 0.8167286 , 0.98235905, 0.06410611, 0.17873585,
          0.07358396, 0.95524645, 0.5906956 , 0.3774085 , 0.9427308 ,
          0.32449841, 0.05033565, 0.6481848 , 0.97997856, 0.7848562 ]]]],
      dtype=float32)>

In [89]:
# tf.squeeze removes all the dimesions with value 1
new_sq = tf.squeeze(sq)
new_sq

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
       0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
       0.01469815, 0.86204493, 0.12014258, 0.91072273, 0.00848019,
       0.62772846, 0.8167286 , 0.98235905, 0.06410611, 0.17873585,
       0.07358396, 0.95524645, 0.5906956 , 0.3774085 , 0.9427308 ,
       0.32449841, 0.05033565, 0.6481848 , 0.97997856, 0.7848562 ],
      dtype=float32)>

# One-Hot Encoding

In [91]:
# One hot encoding with tensors
my_list = [2,3,4,5]

#one hot encoded
tf.one_hot(my_list, depth=6)# depth starts form 0 index

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>